name: Ruby

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.7
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: |
        bundle exec rspec spec --color --format documentation --order random
    - name: Rubocop
      run: |
        bundle exec rubocop -D
